language: node_js

node_js:
  - "0.10"
  #- "0.12"
  #- "iojs"

services:
  - redis-server
  - rabbitmq
  - mongodb
  - elasticsearch

addons:
  code_climate:
    repo_token: b0cf984d93693c3e827901f766ca1f13b6acca03a3786b5e187356e66e8ffbec

env:
  JOOLA_CONFIG_AUTHENTICATION_BASICAUTH_ENABLED=TRUE
  
branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true
  #allow_failures:
  #  - node_js: "0.12"
  #  - node_js: "iojs"

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins list
  - redis-cli flushall

deploy:
  provider: heroku
  on: develop
  app: joola-develop
  api_key:
    secure: u2sgcDddY6is6ZB1q1YsFQwlld0cvsSbfH6UtEVP7QvOeITriv2fauXnt+WTSzLqcLphzFPviUceMP9Qm4FcbKd1+qHHCAtpmZMTx7MXoFjJJXDVYwbL9iQURi5IS6lja8eLSJZk8yonDuWZ6f3babr/iW4o//CalslW5WDwHMs=

script: npm run test:scenario

after_success:
  - npm run test:coverage
  - npm run coveralls
  - npm run codeclimate
  - npm run test:api
 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a43ba3884562555a9c1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false