version: 0.0.8
interfaces:
  webserver:
    enabled: true
    host: joola.io #used for response-header [Server]
    bind: 0.0.0.0
    port: 8080
    securePort: 8081
    secure: true
    keyFile: ./config/certs/localhost.key
    certFile: ./config/certs/localhost.csr
    websocket:
      enabled: true
    sessionDurtaion: 1200000
    timeout: 60000
    blacklist: null
    allowOrigin: null
    headers:
      X-Powered-By: joola.io
  repl:
    enabled: true
    port: 1337
store:
  config:
    redis:
      dsn: redis://127.0.0.1
      ## if dsn not specific then these are required
      # host: 127.0.0.1
      # port: 6379
      # db: 0
      # pass: null
  dispatch:
    redis:
      dsn: redis://127.0.0.1
    stomp:
      dsn: stomp://guest:guest@127.0.0.1:61613
      # if dsn not specific then these are required
      # host: 127.0.0.1
      # port: 61613
      # user: guest
      # pass: guest
  socketio:
    redis:
      dsn: redis://127.0.0.1
  logger:
    console:
      level: trace
    mongo:
      level: trace
      dsn: mongodb://localhost:27017/logger
      # if dsn not specific then these are required
      host: 127.0.0.1
      port: 27017
      user: null
      password: null
      db: logger
      options:
        capped: true
        size: 10240000
      unique: false
      expireAfterSeconds: 3600
    file:
      level: trace
      path: /tmp/joola.io/
  cache:
    mongo:
      dsn: mongodb://localhost:27017/cache
      expireAfterSeconds: 0
dispatch:
    expires: 60
authentication:
  store: internal
  bypassToken: null
  tokens:
    expireAfter: 1200000
#sdk:
  # url: https://raw.githubusercontent.com/joola/joola.io.sdk/feature/%2376/bin/joola.io.js
workspaces:
  root:
    roles:
      root:
        key: "root"
        _permissions:
          - "access_system"
          - "manage_system"
          - "manage_users"
          - "beacon_insert"
          - "query_fetch"
        _filter: ""
      user:
        key: "user"
        _permissions:
          - "access_system"
        _filter: ""
      beacon:
        key: "user"
        _permissions:
          - "beacon_insert"
        _filter: ""
      reader:
        key: "user"
        _permissions:
          - "access_system"
          - "beacon_insert"
        _filter: ""
    users:
      root:
        username: "root"
        _password: "password"
        _roles:
          - "root"
        displayName: "Administrator"
        workspace: "root"
        _APIToken: "apitoken-root"
        su: true
        rateLimit: 5000
      beacon:
        username: "beacon"
        _password: "password"
        _roles:
          - "beacon"
        displayName: "Beacon"
        workspace: "root"
        _APIToken: "apitoken-beacon"
        su: true
      reader:
        username: "reader"
        _password: "password"
        _roles:
          - "reader"
        displayName: "Reader"
        workspace: "root"
        _APIToken: "apitoken-reader"
        su: true
    collections:
      stats-node-count:
        key: "stats-node-count"
        name: "stats-node-count"
        strongTyped: true
        expireAfterSeconds: 3600
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        node:
          datatype: "string"
          type: "dimension"
          name: "node"
          key: "node"
        event:
          datatype: "string"
          type: "dimension"
          name: "event"
          key: "event"
        nodes:
          datatype: "number"
          type: "metric"
          name: "nodes"
          key: "nodes"
      stats-token-count:
        key: "stats-token-count"
        name: "stats-token-count"
        strongTyped: true
        expireAfterSeconds: 3600
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        node:
          datatype: "string"
          type: "dimension"
          name: "node"
          key: "node"
        event:
          datatype: "string"
          type: "dimension"
          name: "event"
          key: "event"
        tokens:
          datatype: "number"
          type: "metric"
          name: "tokens"
          key: "tokens"
      stats-usage:
        key: "stats-usage"
        name: "stats-usage"
        strongTyped: true
        expireAfterSeconds: 3600
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        node:
          datatype: "string"
          type: "dimension"
          name: "node"
          key: "node"
        event:
          datatype: "string"
          type: "dimension"
          name: "event"
          key: "event"
        cpu:
          datatype: "number"
          type: "metric"
          name: "cpu"
          key: "cpu"
        mem:
          datatype: "number"
          type: "metric"
          name: "mem"
          key: "mem"
      stats-events-request:
        key: "stats-events-request"
        name: "stats-events-request"
        strongTyped: true
        expireAfterSeconds: 3600
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        node:
          datatype: "string"
          type: "dimension"
          name: "node"
          key: "node"
        event:
          datatype: "string"
          type: "dimension"
          name: "event"
          key: "event"
        events:
          datatype: "number"
          type: "metric"
          name: "events"
          key: "events"
      stats-events-fulfilled:
        key: "stats-events-fulfilled"
        name: "stats-events-fulfilled"
        strongTyped: true
        expireAfterSeconds: 3600
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        node:
          datatype: "string"
          type: "dimension"
          name: "node"
          key: "node"
        event:
          datatype: "string"
          type: "dimension"
          name: "event"
          key: "event"
        fulfilled:
          datatype: "number"
          type: "metric"
          name: "fulfilled"
          key: "fulfilled"
        fulfilledtime:
          datatype: "number"
          type: "metric"
          name: "fulfilledtime"
          key: "fulfilledtime"
      demo-visits:
        key: "demo-visits"
        name: "demo-visits"
        strongTyped: true
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        browser:
          datatype: "string"
          type: "dimension"
          name: "browser"
          key: "browser"
        engine:
          datatype: "string"
          type: "dimension"
          name: "engine"
          key: "engine"
        os:
          datatype: "string"
          type: "dimension"
          name: "os"
          key: "os"
        userid:
          datatype: "string"
          type: "dimension"
          name: "userid"
          key: "userid"
        ip:
          datatype: "ip"
          type: "dimension"
          name: "ip"
          key: "ip"
        referrer:
          datatype: "string"
          type: "dimension"
          name: "referrer"
          key: "referrer"
        visits:
          datatype: "number"
          type: "metric"
          name: "visits"
          key: "visits"
          min: 0
          max: 1
        loadtime:
          datatype: "number"
          type: "metric"
          name: "loadtime"
          key: "loadtime"
          min: 0
          max: 10000
      demo-clicks:
        key: "demo-clicks"
        name: "demo-clicks"
        strongTyped: true
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        browser:
          datatype: "string"
          type: "dimension"
          name: "browser"
          key: "browser"
        engine:
          datatype: "string"
          type: "dimension"
          name: "engine"
          key: "engine"
        os:
          datatype: "string"
          type: "dimension"
          name: "os"
          key: "os"
        userid:
          datatype: "string"
          type: "dimension"
          name: "userid"
          key: "userid"
        ip:
          datatype: "ip"
          type: "dimension"
          name: "ip"
          key: "ip"
        referrer:
          datatype: "string"
          type: "dimension"
          name: "referrer"
          key: "referrer"
        clicks:
          datatype: "number"
          type: "metric"
          name: "clicks"
          key: "clicks"
          min: 0
          max: 1
      demo-mousemoves:
        key: "demo-mousemoves"
        name: "demo-mousemoves"
        strongTyped: true
        timestamp:
          datatype: "date"
          type: "dimension"
          name: "timestamp"
          key: "timestamp"
        browser:
          datatype: "string"
          type: "dimension"
          name: "browser"
          key: "browser"
        engine:
          datatype: "string"
          type: "dimension"
          name: "engine"
          key: "engine"
        os:
          datatype: "string"
          type: "dimension"
          name: "os"
          key: "os"
        userid:
          datatype: "string"
          type: "dimension"
          name: "userid"
          key: "userid"
        ip:
          datatype: "ip"
          type: "dimension"
          name: "ip"
          key: "ip"
        referrer:
          datatype: "string"
          type: "dimension"
          name: "referrer"
          key: "referrer"
        mousemoves:
          datatype: "number"
          type: "metric"
          name: "mousemoves"
          key: "mousemoves"
          min: 0
          max: 1000
