version: "0.0.1"
general:
  adminemail: "admin@domain.com"
  dateformat: "YYYY-mm-dd hh:ii:ss"
  systemname: "joola.io"

interfaces:
  webserver:
    enabled: true
    host: "127.0.0.1"
    port: 8080
    securePort: 8081
    secure: false
    keyFile: null
    certFile: null
    websocket:
      enabled: true
    sessionDurtaion: 1200000
    timeout: 60000
    blacklist: null
  repl:
    enabled: true
    port: 1337

store:
  config:
    redis:
      host: "127.0.0.1"
      port: 6379
      db: 0
      pass: null
  dispatch:
    redis:
      host: "127.0.0.1"
      port: 6379
      db: 0
      pass: null
    stomp:
      host: "127.0.0.1"
      port: 61613
      user: "guest"
      pass: "guest"

dispatch:
    expires: 60
